baseURL = "/"
languageCode = "en-us"
title = "Lavandería autoservicio Villaverde Bajo"
theme = "ananke"

DefaultContentLanguage = "en"
SectionPagesMenu = "main"
Paginate = 5 # this is set low for demonstrating with dummy content. Set to a higher number
googleAnalytics = ""
enableRobotsTXT = true
contentDir = "content"

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  favicon = ""
  site_logo = ""
  description = "Lavandería Autoservicio Colada Exprés - Villaverde Bajo"
  twitter = "https://twitter.com/lavavillabajo"
  rss = ""
  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-black"
  featured_image = "/images/Common/Local.jpg"
  recent_posts_number = 2